### Mathematics of ML — Day 1

1. Vector
→ Ordered collection of numbers.

2. Matrix
→ Numbers arranged in rows and columns.

3. Matrix dimension
→ rows × columns

4. Scalar multiplication
→ Multiply every element by the scalar.

5. Matrix multiplication

(m×n)(n×p)→(m×p)
Compare inner dimensions
They must be equal
Result uses outer dimensions
Calculate using row × column
Multiply → add

6. Special matrices

Zero matrix → all 0
Identity matrix → diagonal 1, rest 0
Diagonal matrix → non-diagonal elements are 0

In [3]:
import numpy as np

In [4]:
a = np.array([[1,2],[3,4]])
b= np.array([[3,6],[7,8]])

In [8]:
print("ADD :\n",a+b)

ADD :
 [[ 4  8]
 [10 12]]


In [9]:
print("Sub :\n",a-b)

Sub :
 [[-2 -4]
 [-4 -4]]


Scaler multlipication

In [10]:
c= 2 * a

In [11]:
print("Scaler multlipication :\n",c)

Scaler multlipication :
 [[2 4]
 [6 8]]


### matrix multiplication

In [12]:
result = np.dot(a,b)
print("matrix multiplication :\n",result)

matrix multiplication :
 [[17 22]
 [37 50]]


### special matrix(I)

#### indentity matrix

In [14]:
i = np.eye(2)
print("Identity matrix : \n" , i*a)


Identity matrix : 
 [[1. 0.]
 [0. 4.]]


#### zero matrix

In [15]:
z = np.zeros((2,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


### Diagonal matrix 

In [16]:
d =np.diag([1,2,3])
print("Diagonal matrix:\n",d)

Diagonal matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


### create vectors and matrix using numpy

In [17]:
c= np.array([[1,2],[3,4]])
d=np.array([[7,8],[9,10]])

print("Addition:\n" ,a+b)
print("subition:\n ",a-b)

Addition:
 [[ 4  8]
 [10 12]]
subition:
  [[-2 -4]
 [-4 -4]]


In [18]:
### scalaer matrics
print("Scaler matrixies:\n" ,3*a)

Scaler matrixies:
 [[ 3  6]
 [ 9 12]]


### implement matrix values 

In [20]:
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
v=np.array([1,0,-1])

### matrix -vector 

In [21]:
res = np.dot(m,v)
print("result matrix :\n" , res)

result matrix :
 [-2 -2 -2]


## explore the matrics 

In [23]:
I= np.eye (3)
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("A * I :\n",np.dot(A,I))

A * I :
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


### diagonal and zero

In [24]:
D= np.diag([1,7,9])
Z=np.zeros((3,3))

print("digional matrix :\n",D)
print("zero matrix:\n",Z)

digional matrix :
 [[1 0 0]
 [0 7 0]
 [0 0 9]]
zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
